---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-kong-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: inventory-kongingress
    configuration.konghq.com: inventory-kongingress
  namespace: team2-staging
spec:
  rules:
    - host: kong-staging.istio.dev1.eks.openshiftlabs.net
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: inventory
                port:
                  number: 8080

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: inventory-kongingress
  namespace: team2-staging
route:
  preserve_host: false
upstream:
  host_header: inventory.team2-staging.svc                   