apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: basket
  namespace: team2-prd
spec:
  interval: 1m
  releaseName: basket
  targetNamespace: team2-prd
  chart:
    spec:
      chart: microservice
      version: '1.0.12'
      sourceRef:
        kind: HelmRepository
        name: team2-helmrepo-prd
        namespace: team2-prd
      interval: 1m
  values:
    platform: ocp
    versionlabel: v1
    applabel: flux
    image_reg: 005459661421.dkr.ecr.eu-west-2.amazonaws.com
    image_name: basket
    image_tag: latest
    containerport: 8080
    spring_active_profile: dev
    replicas: 1 
    container:
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
      - name: inventory.host
        value: inventory:8080
      - name: user.host
        value: user:8080
      - name: basket.host
        value: basket:8080     
    trigger: 19

